In [3]:
#1.1生成Numpy數組
import numpy as np

In [4]:
#1.1.1從已有數據中創建數組
lst1 = [3.14, 2.17, 0, 1, 2]
nd1 = np.array(lst1)
type(nd1)

numpy.ndarray

In [5]:
lst2 = [[3.14, 2.17], [0, 1, 2]]
nd2 = np.array(lst2)
type(nd2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  


numpy.ndarray

In [7]:
#1.1.2利用random模塊產生數組

nd3 = np.random.random([3, 3])
print(nd3)
type(nd3.shape)

[[0.16309345 0.78511622 0.970346  ]
 [0.11441756 0.08298159 0.52454435]
 [0.60300165 0.61942013 0.15484608]]


tuple

In [8]:
np.random.seed(123)
nd4 = np.random.randn(2, 3)
print(nd4)
np.random.shuffle(nd4)
print(nd4)

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]


In [9]:
#1.1.3創建特定形狀的多維數組
nd5 = np.zeros([3, 3])
nd6 = np.ones([3, 3])
nd7 = np.eye(3)
nd8 = np.diag([1, 2, 3])
print(nd5)
print(nd6)
print(nd7)
print(nd8)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
#1.1.4利用arrange, linspace函數生成數組
print(np.arange(10))
print(np.arange(0, 10))
print(np.arange(1, 4, 0.5))
print(np.arange(9, -1, -1))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5]
[9 8 7 6 5 4 3 2 1 0]


In [12]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
#1.2獲取元素
np.random.seed(2019)
nd11 = np.random.random([10])
nd11[3]
nd11[3:6]
nd11[1:6:2]
nd11[::-2]

nd12 = np.arange(25).reshape([5, 5])

In [17]:
#1.3.1對應元素相乘
A = np.array([[1, 2], [-1, 4]])
B = np.array([[2, 0], [3, 4]])

print(A * B)
np.multiply(A, B)

[[ 2  0]
 [-3 16]]


array([[ 2,  0],
       [-3, 16]])

In [18]:
print(A*2.0)
A/2.0

[[ 2.  4.]
 [-2.  8.]]


array([[ 0.5,  1. ],
       [-0.5,  2. ]])

In [21]:
#1.3.2點積運算
X1 = np.array([[1, 2], [3, 4]])
X2 = np.array([[5, 6], [7, 8, 9]])
np.dot(X1, X2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


array([list([5, 6, 7, 8, 9, 7, 8, 9]),
       list([5, 6, 5, 6, 5, 6, 7, 8, 9, 7, 8, 9, 7, 8, 9, 7, 8, 9])],
      dtype=object)

In [22]:
#1.4數組變形
#1.reshape
arr = np.arange(10)
print(arr.reshape(2, 5))
print(arr.reshape(5, -1))
arr.reshape(-1, 5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
#2.resize
arr = np.arange(10)
arr.resize(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
#3.T
arr = np.arange(12).reshape(3, 4)
print(arr)
arr.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [26]:
#4.ravel
arr = np.arange(6).reshape(2, -1)
print(arr.ravel('F'))
arr.ravel()

[0 3 1 4 2 5]


array([0, 1, 2, 3, 4, 5])

In [27]:
#5.flatten
a = np.floor(10 * np.random.random((3, 4)))
print(a)
a.flatten()

[[4. 2. 1. 8.]
 [1. 9. 0. 5.]
 [2. 8. 5. 5.]]


array([4., 2., 1., 8., 1., 9., 0., 5., 2., 8., 5., 5.])

In [28]:
#6.squeeze
arr = np.arange(3).reshape(3, 1)
print(arr.shape)
arr.squeeze().shape

(3, 1)


(3,)

In [29]:
#7.transpose
arr2 = np.arange(24).reshape(2, 3, 4)
print(arr2.shape)
arr2.transpose(1, 2, 0).shape

(2, 3, 4)


(3, 4, 2)

In [31]:
#1.4.2合併數組
#1.append
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.append(a, b)

array([1, 2, 3, 4, 5, 6])

In [33]:
#2.concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b.T), axis=1))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [34]:
#3.stack
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.stack((a, b), axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [36]:
#1.7廣播機制
A = np.arange(0, 40, 10).reshape(4, 1)
B = np.arange(0, 3)
A + B

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])