Tensors 类似于 NumPy 的 ndarrays ，同时 Tensors 可以使用 GPU 进行计算。

In [1]:
from __future__ import print_function
import torch

#构造一个5x3矩阵，不初始化。
x = torch.empty(5, 3)
x

tensor([[1.4098e-27, 3.0739e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0739e-41],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 3.5886e-28]])

In [2]:
#构造一个随机初始化的矩阵
x = torch.rand(5, 3)
x

tensor([[0.4947, 0.5481, 0.5498],
        [0.1228, 0.0308, 0.9358],
        [0.8602, 0.8374, 0.7785],
        [0.2562, 0.7575, 0.2960],
        [0.1464, 0.4797, 0.0121]])

In [3]:
#构造一个矩阵全为 0，而且数据类型是 long.
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [4]:
#构造一个张量，直接使用数据
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [5]:
#创建一个 tensor 基于已经存在的 tensor
x = x.new_ones(5, 3, dtype=torch.double)      
# new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    
# override dtype!
print(x)                                      
# result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.2837, -0.9420, -0.6175],
        [-0.5147,  0.4332,  0.0164],
        [-1.4816, -0.9543,  0.6989],
        [-0.4676,  0.8969,  1.8800],
        [ 0.7761, -2.7623,  0.2752]])


In [6]:
#获取它的维度信息
x.size()

torch.Size([5, 3])

**操作**

在接下来的例子中，我们将会看到加法操作。 加法: 方式 1

In [8]:
y = torch.rand(5, 3)
x + y

tensor([[1.4193, 0.9079, 0.7519],
        [1.0739, 1.8773, 1.2288],
        [1.0157, 0.9883, 1.2366],
        [0.9179, 0.8186, 0.4702],
        [1.3655, 1.3047, 0.9609]])

In [9]:
#加法: 方式2
torch.add(x, y)

tensor([[1.4193, 0.9079, 0.7519],
        [1.0739, 1.8773, 1.2288],
        [1.0157, 0.9883, 1.2366],
        [0.9179, 0.8186, 0.4702],
        [1.3655, 1.3047, 0.9609]])

In [10]:
#加法: 提供一个输出 tensor 作为参数
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[1.4193, 0.9079, 0.7519],
        [1.0739, 1.8773, 1.2288],
        [1.0157, 0.9883, 1.2366],
        [0.9179, 0.8186, 0.4702],
        [1.3655, 1.3047, 0.9609]])

In [11]:
#加法: in-place
y.add_(x)

tensor([[1.4193, 0.9079, 0.7519],
        [1.0739, 1.8773, 1.2288],
        [1.0157, 0.9883, 1.2366],
        [0.9179, 0.8186, 0.4702],
        [1.3655, 1.3047, 0.9609]])