In [1]:
#1.2.2 pytorch安装验证
import torch

print(torch.__version__)
print(torch.cuda.is_available)
print(torch.version.cuda)

1.10.0+cu111
<function is_available at 0x7fb41ceab3b0>
11.1


索引数量	计算机科学中的名称	数学中的名称	Tensor表示

0	数字	标量	0维张量

1	数组	矢量	1维张量

2	二维数组	矩阵	2维张量

n	N维数组	N维张量	n维张量

In [2]:
#2.1 张量介绍
t = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [3]:
#2.2 张量的属性(秩，轴，形状)
t = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
type(t) 

torch.Tensor

In [4]:
t.shape

torch.Size([3, 3])

In [5]:
rank = len(t.shape)
rank

2

In [6]:
t.reshape(9, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [7]:
#2.4.1 张量的属性
t = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


2.4.2 关于张量的两件事

张量是包含一个同一类型的数据

张量之间的计算依赖于类型和设备

In [9]:
import numpy as np

t = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(torch.Tensor(t))           # 类构造函数
print(torch.tensor(t))           # 工厂函数
print(torch.as_tensor(t))        # 工厂函数
print(torch.from_numpy(t))       # 工厂函数

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


工厂函数：接受参数输入并返回特定类型对象的函数；

工厂函数允许更多的动态对象创建；具有更好的文档，并有更多的配置参数；

通常情况下会更倾向于选择工厂函数

In [10]:
#2.4.4 无数据情况下创建张量
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
torch.rand(3, 3)

tensor([[0.3096, 0.0781, 0.4683],
        [0.3013, 0.8592, 0.9429],
        [0.0034, 0.5752, 0.6450]])

2.5 数据创建pytorch张量的四种方法的区别

pytorch张量是torch.tensor pytorch类的实例

一个张量的抽象概念和一个pytorch张量的区别在于：pytorch张量给了我们一个具体的实现，我们可以使用和编码它

In [14]:
#2.5.1 四种方法的区别1：数据类型
data = np.array([1,2,3])
t1 = torch.Tensor(data)
print(t1)
print(t1.dtype)
t2 = torch.tensor(data)
print(t2)
print(t2.dtype)
t3 = torch.as_tensor(data)
print(t3)
print(t3.dtype)
t4 = torch.from_numpy(data)
print(t4)
print(t4.dtype)

tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3])
torch.int64
tensor([1, 2, 3])
torch.int64
tensor([1, 2, 3])
torch.int64


上述使用类构造函数和工厂函数后生成的数据类型不同，主要原因是：构造函数在构造一个张量时使用全局缺省值，而工厂函数通过输入数据的类型来推断输出数据的类型

In [15]:
# 查看全局缺省值的数据类型
d = torch.get_default_dtype
d

<function torch._C.get_default_dtype>

In [17]:
# 工厂函数可以显示指定数据类型，类构造函数不能这样操作
t = torch.tensor(np.array([1,2,3]), dtype=torch.float64)
t

tensor([1., 2., 3.], dtype=torch.float64)

In [18]:
#2.5.2 四种方法的区别2：数据分配内存方式
data = np.array([1,2,3])
print(data)

t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

data[0] = 0
data[1] = 0
data[2] = 0

# t1 和 t2 输出的都是更改前的数组
print(t1)
print(t2)
# t3 和 t4 输出的都是更改后的数组
print(t3)
print(t4)

[1 2 3]
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([0, 0, 0])


上述差异是由创建时分配内存的方式造成的：t1和t2的方式是将数组中的元素值直接拷贝到张量中，改变data中的元素值并不会影响到t1和t2中的值；t3和t4的方式是与data数组共享数据；（可将t1和t2的方式看作"值传递"；t3和t4的方式看作“地址传递”） | 共享数据 | 数据拷贝 | |:-----------------|:----------------| | torch.as_tensor() | torch.tensor()| | torch.from_numpy()| torch.Tensor()|

由上可知numpy和tensor是数据共享的，所以他们可以无缝切换

数据共享比数据拷贝更高效，更节省内存空间

2.6 张量的重塑操作(reshaping)

2.6.1 常用张量操作类型

Reshaping operations

Element-wise operations

Reduction operations

Access operations #### 2.6.2 张量的重塑

张量的重塑是最重要的张量操作：因为张量的形状能提供给我们一些具体的东西，我们可以用它来塑造和直观的理解张量

In [19]:
t = torch.tensor([[1,1,1,1],
                 [2,2,2,2],
                  [3,3,3,3]], dtype=torch.float32)
print(t.size)
print(t.shape)

<built-in method size of Tensor object at 0x7fb417aa9890>
torch.Size([3, 4])


In [20]:
# 得到张量中的元素个数
# 方法1：
torch.tensor(t.shape).prod()

tensor(12)

In [21]:
# 方法2：
t.numel() 

12

In [22]:
# 张量的reshape,squeezing和unsqueezing
print(t.reshape(1,12))
print(t.reshape(1,12).shape)
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [23]:
# 张量的flatten
t = torch.tensor([[1,1,1,1],
                 [2,2,2,2],
                  [3,3,3,3]], dtype=torch.float32)
# 方法1：
def flatten(t):
  t1 = t.reshape(1, -1)
  t1 = t1.squeeze()
  return t1
flatten(t)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [24]:
# 方法2：
t2 = t.reshape(1,-1)[0]
print(t2)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


In [25]:
# 方法3：
t3 = t.reshape(-1)
t3

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [26]:
# 方法4：
t4 = t.view(t.numel())
t4

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [27]:
# 方法5：
t5 = t.flatten()
t5

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [28]:
#2.7 多批次张量的flatten
# t1,t2,t3为三个4x4的图像
t1 = torch.tensor([
            [1,1,1,1],
            [1,1,1,1],
            [1,1,1,1],
            [1,1,1,1]
        ])

t2 = torch.tensor([
            [2,2,2,2],
            [2,2,2,2],
            [2,2,2,2],
            [2,2,2,2]
        ])

t3 = torch.tensor([
            [3,3,3,3],
            [3,3,3,3],
            [3,3,3,3],
            [3,3,3,3]
        ])
# 使用stack将其合并成一个秩为3的张量
t = torch.stack((t1,t2,t3))
print(t.shape)    
# 增加一个彩色通道轴，将其变成CNN期望的形式，以上三张图像均为灰度图像
t = t.reshape(3,1,4,4)
print(t[0])    # 第一个图像
print(t[0][0])     # 第一个图像的第一个通道
print(t[0][0][0])  # 第一个图像的第一个通道中的第一行像素
print(t[0][0][0][0])   # 第一个图像的第一个通道中的第一行的第一个像素

# 该张量的flatten:我们期望只将图像张量flatten，而不是全部flatten
print(t.flatten(start_dim=1).shape)  
print(t.flatten(start_dim=1))  # 参数start_dim告诉flatten函数应该从哪个轴开始

torch.Size([3, 4, 4])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([1, 1, 1, 1])
tensor(1)
torch.Size([3, 16])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])


2.8 张量的操作

2.8.1 张量的元素运算(element-wise operation)

元素运算是对张量元素的运算，这些元素在张量中对应或具有相同的位置索引
两个张量必须有相同的形状才能执行元素操作

In [29]:
t1 = torch.tensor([
                [1,2],
                [3,4]
            ], dtype=torch.float32)

t2 = torch.tensor([
                [9,8],
                [7,6]
            ], dtype=torch.float32)

print(t1 + t2)
print(t1 + 2)
print(t1 - 2)
print(t1 * 2)
print(t1 / 2)

tensor([[10., 10.],
        [10., 10.]])
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


2.8.2 张量的广播

张量的广播：定义了在元素操作的过程中如何处理不同形状的张量，即：将标量变成与另一个张量相同的形状

张量广播在数据标准化时会常用到

In [30]:
t1 = torch.tensor([
                [1,1],
                [1,1]
            ])
t2 = torch.tensor([2,4])
print(t1+t2)
np.broadcast_to(t2.numpy,t1.shape) #广播
t1 + t2

tensor([[3, 5],
        [3, 5]])


tensor([[3, 5],
        [3, 5]])

2.9 张量的缩减操作（reduction）

缩减操作是一个减少张量中包含的元素数量的操作

元素操作允许我们对多个张量进行操作；缩减操作允许我们对单个张量进行操作

In [31]:
t = torch.tensor([
                [0,1,0],
                [2,0,2],
                [0,3,0]
            ], dtype = torch.float32)
print(t.sum()) 
print(t.numel())  
print(t.sum().numel()) 
print(t.sum().numel() < t.numel())  

tensor(8.)
9
1
True


In [32]:
# 缩减操作通常允许跨数据结构计算总值
# 对某个轴进行缩减操作
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)
t.sum(dim=0)

tensor([6., 6., 6., 6.])

In [33]:
t.sum(dim=1)

tensor([ 4.,  8., 12.])

argmax函数：得到张量的最大输出值的对应索引位置

在实际应用中，经常在神经网络输出预测张量上使用argmax，确定哪个类别的预测最高

In [35]:
t = torch.tensor([
                [1,0,0,2],
                [0,3,3,0],
                [4,0,0,5]
            ], dtype=torch.float32)
t.max()

tensor(5.)

In [36]:
t.argmax()            # 输出的是flatten后的索引

tensor(11)