In [1]:
import torch

In [2]:
a = torch.randint(1,5,(2,3))
b = torch.randint(1,5,(2,3))
print(a)
print(b)

tensor([[1, 3, 3],
        [3, 3, 1]])
tensor([[4, 1, 2],
        [4, 1, 3]])


In [3]:
a + b

tensor([[5, 4, 5],
        [7, 4, 4]])

In [4]:
torch.add(a,b)

tensor([[5, 4, 5],
        [7, 4, 4]])

In [5]:
result = torch.zeros(2,3)
torch.add(a,b,out=result)

tensor([[5., 4., 5.],
        [7., 4., 4.]])

In [6]:
result

tensor([[5., 4., 5.],
        [7., 4., 4.]])

In [7]:
# a = a + b
# 注意 任何使张量tensor会发生变化的操作都有一个前缀'_'，例如：a.add_(),b.sub_()
a.add_(b)
a

tensor([[5, 4, 5],
        [7, 4, 4]])

In [8]:
a - b

tensor([[1, 3, 3],
        [3, 3, 1]])

In [9]:
a * b

tensor([[20,  4, 10],
        [28,  4, 12]])

In [10]:
a / b

tensor([[1, 4, 2],
        [1, 4, 1]])

In [11]:
# 取余数
a % b

tensor([[1, 0, 1],
        [3, 0, 1]])

In [12]:
# 取整
a // b

tensor([[1, 4, 2],
        [1, 4, 1]])

In [14]:
tensor = torch.ones(3,5)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
a

tensor([[5, 4, 5],
        [7, 4, 4]])

In [16]:
torch.matmul(a,tensor)

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'mat2' in call to _th_mm

In [17]:
a.dtype

torch.int64

In [18]:
tensor.dtype

torch.float32

In [21]:
a = a.float()
a.dtype

torch.float32

In [22]:
torch.matmul(a,tensor) # 2*3 3*5 = 2*5

tensor([[14., 14., 14., 14., 14.],
        [15., 15., 15., 15., 15.]])

In [23]:
a.T

tensor([[5., 7.],
        [4., 4.],
        [5., 4.]])