In [1]:
import torch

In [2]:
sample = torch.rand(3,2)

In [3]:
sample

tensor([[0.3326, 0.4266],
        [0.2649, 0.0896],
        [0.1097, 0.0581]])

In [4]:
torch.sum(sample)

tensor(1.2814)

In [5]:
torch.min(sample)

tensor(0.0581)

In [6]:
torch.max(sample)

tensor(0.4266)

In [7]:
# 求最小值所在的位置（索引）
torch.argmin(sample)

tensor(5)

In [8]:
# 求最大值所在的位置（索引）
torch.argmax(sample)

tensor(1)

In [9]:
torch.mean(sample)

tensor(0.2136)

In [10]:
torch.median(sample)

tensor(0.1097)

In [11]:
torch.sqrt(sample)

tensor([[0.5767, 0.6531],
        [0.5146, 0.2994],
        [0.3312, 0.2410]])

In [14]:
sample ** 2

tensor([[0.1106, 0.1820],
        [0.0701, 0.0080],
        [0.0120, 0.0034]])