In [25]:
import torch

In [26]:
x = torch.ones((2,2),requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [27]:
y = x + 2
y.requires_grad=True

RuntimeError: you can only change requires_grad flags of leaf variables.

In [24]:
z = y * y * 3

In [17]:
out = z.mean()

In [18]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [19]:
out.backward()

In [20]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You should have got a matrix of ``4.5``. Let’s call the ``out``
*Tensor* “$o$”.
We have that $o = \frac{1}{4}\sum_i z_i$,
$z_i = 3(x_i+2)^2$ and $z_i\bigr\rvert_{x_i=1} = 27$.
Therefore,
$\frac{\partial o}{\partial x_i} = \frac{3}{2}(x_i+2)$, hence
$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$.

In [21]:
print(y.grad)

None


tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)